-- Gerado por gerar_tbl_codigos_from_dicionario.js a partir de Dezembro/dicionariotudo.csv
-- Tabela auxiliar para cruzar códigos numéricos com descritores (sexo, escolaridade, raça, etc.)

INSERT INTO tbl_codigos_cadu (nome_campo, cod, descricao) VALUES
('d_cod_est_cadastral_fam', '2', 'Sem Registro Civil'),
('d_cod_est_cadastral_fam', '3', 'Cadastrado'),
('d_cod_forma_coleta_fam', '0', 'Informacao migrada como inexistente'),
('d_cod_forma_coleta_fam', '1', 'Sem visita Domiciliar'),
('d_cod_forma_coleta_fam', '2', 'Com visita domiciliar'),
('d_fx_rfpc', '1', 'Ate R$89,00'),
('d_fx_rfpc', '2', 'Entre R$85,01 ate R$178,00'),
('d_fx_rfpc', '3', 'Entre R$178,01 ate 1/2 S.M.'),
('d_fx_rfpc', '4', 'Acima de 1/2 S.M.'),
('d_marc_pbf', '0', 'Nao'),
('d_marc_pbf', '1', 'Sim'),
('d_qtde_meses_desat_cat', '0', 'ate 12 Meses'),
('d_qtde_meses_desat_cat', '1', '13 a 18 Meses'),
('d_qtde_meses_desat_cat', '2', '19 a 24 Meses'),
('d_qtde_meses_desat_cat', '3', '25 a 36 Meses'),
('d_qtde_meses_desat_cat', '4', '37 a 48 Meses'),
('d_qtde_meses_desat_cat', '5', 'acima de 48 Meses'),
('d_cod_local_domic_fam', '1', 'Urbanas'),
('d_cod_local_domic_fam', '2', 'Rurais'),
('d_cod_especie_domic_fam', '1', 'Particular Permanente'),
('d_cod_especie_domic_fam', '2', 'Particular improvisado'),
('d_cod_especie_domic_fam', '3', 'Coletivo'),
('d_cod_material_piso_fam', '1', 'Terra'),
('d_cod_material_piso_fam', '2', 'Cimento'),
('d_cod_material_piso_fam', '3', 'aplicacoes.mds.gov.br/sagi/simulacao/cecadAdm/ Madeira aproveitada'),
('d_cod_material_piso_fam', '4', 'Madeira aparelhada'),
('d_cod_material_piso_fam', '5', 'Ceramica, lajota ou pedra'),
('d_cod_material_piso_fam', '6', 'Carpete'),
('d_cod_material_piso_fam', '7', 'Outro Material'),
('d_cod_material_domic_fam', '1', 'Alvenaria/tijolo com revestimento'),
('d_cod_material_domic_fam', '2', 'Alvenaria/tijolo sem revestimento'),
('d_cod_material_domic_fam', '3', 'Madeira aparelhada'),
('d_cod_material_domic_fam', '4', 'Taipa revestida'),
('d_cod_material_domic_fam', '5', 'Taipa nao revestida'),
('d_cod_material_domic_fam', '6', 'Madeira aproveitada'),
('d_cod_material_domic_fam', '7', 'Palha'),
('d_cod_material_domic_fam', '8', 'Outro Material'),
('d_cod_agua_canalizada_fam', '1', 'Sim'),
('d_cod_agua_canalizada_fam', '2', 'Nao'),
('d_cod_abaste_agua_domic_fam', '1', 'Rede geral de distribuicao'),
('d_cod_abaste_agua_domic_fam', '2', 'Poco ou nascente'),
('d_cod_abaste_agua_domic_fam', '3', 'Cisterna'),
('d_cod_abaste_agua_domic_fam', '4', 'Outra forma'),
('d_cod_banheiro_domic_fam', '1', 'Sim'),
('d_cod_banheiro_domic_fam', '2', 'Nao'),
('d_cod_escoa_sanitario_domic_fam', '1', 'Rede coletora de esgoto ou pluvial'),
('d_cod_escoa_sanitario_domic_fam', '2', 'Fossa septica'),
('d_cod_escoa_sanitario_domic_fam', '3', 'Fossa rudimentar'),
('d_cod_escoa_sanitario_domic_fam', '4', 'Vala a ceu aberto'),
('d_cod_escoa_sanitario_domic_fam', '5', 'Direto para um rio, lago ou mar'),
('d_cod_escoa_sanitario_domic_fam', '6', 'Outra forma'),
('d_cod_destino_lixo_domic_fam', '1', 'E coletado diretamente'),
('d_cod_destino_lixo_domic_fam', '2', 'E coletado indiretamente'),
('d_cod_destino_lixo_domic_fam', '3', 'E queimado ou enterrado na propriedade'),
('d_cod_destino_lixo_domic_fam', '4', 'E jogado em terreno baldio ou logradouro (rua, avenida, etc.)'),
('d_cod_destino_lixo_domic_fam', '5', 'E jogado em rio ou mar'),
('d_cod_destino_lixo_domic_fam', '6', 'Tem outro destino'),
('d_cod_iluminacao_domic_fam', '1', 'Eletrica com medidor proprio'),
('d_cod_iluminacao_domic_fam', '2', 'Eletrica com medidor comunitario'),
('d_cod_iluminacao_domic_fam', '3', 'Eletrica sem medidor'),
('d_cod_iluminacao_domic_fam', '4', 'Oleo, querosene ou gas'),
('d_cod_iluminacao_domic_fam', '5', 'Vela'),
('d_cod_iluminacao_domic_fam', '6', 'Outra forma'),
('d_cod_calcamento_domic_fam', '1', 'Total'),
('d_cod_calcamento_domic_fam', '2', 'Parcial'),
('d_cod_calcamento_domic_fam', '3', 'Nao existe'),
('d_cod_familia_indigena_fam', '1', 'Sim'),
('d_cod_familia_indigena_fam', '2', 'Nao'),
('d_cod_indigena_reside_fam', '1', 'Sim'),
('d_cod_indigena_reside_fam', '2', 'Nao'),
('d_ind_familia_quilombola_fam', '1', 'Sim'),
('d_ind_familia_quilombola_fam', '2', 'Nao'),
('d_ind_risco_scl_inseg_alim', '1', 'Sim'),
('d_ind_risco_scl_inseg_alim', '2', 'Nao'),
('d_ic_tipo_contato_1_fam', 'L', 'Celular'),
('d_ic_tipo_contato_1_fam', 'C', 'Trabalho'),
('d_ic_tipo_contato_1_fam', 'R', 'Residencial'),
('d_ic_tipo_contato_1_fam', 'O', 'Recado'),
('d_ic_tipo_contato_1_fam', 'N', 'Nao tem'),
('d_ic_tipo_contato_1_fam', 'D', 'Nao declarado'),
('d_ic_tipo_contato_1_fam', 'S', 'Sem coleta de dados.'),
('d_ic_envo_sms_contato_1_fam', 'S', 'Sim'),
('d_ic_envo_sms_contato_1_fam', 'N', 'Nao'),
('d_ic_tipo_contato_2_fam', 'L', 'Celular'),
('d_ic_tipo_contato_2_fam', 'C', 'Trabalho'),
('d_ic_tipo_contato_2_fam', 'R', 'Residencial'),
('d_ic_tipo_contato_2_fam', 'O', 'Recado'),
('d_ic_tipo_contato_2_fam', 'N', 'Nao tem'),
('d_ic_tipo_contato_2_fam', 'D', 'Nao declarado'),
('d_ic_tipo_contato_2_fam', 'S', 'Sem coleta de dados.'),
('d_ic_envo_sms_contato_2_fam', 'S', 'Sim'),
('d_ic_envo_sms_contato_2_fam', 'N', 'Nao'),
('d_ind_parc_mds_fam', '101', 'Famlia Cigana'),
('d_ind_parc_mds_fam', '201', 'Familia Extrativista'),
('d_ind_parc_mds_fam', '202', 'Familia de Pescadores  Artesanais'),
('d_ind_parc_mds_fam', '203', 'Familia Pertencente a Comunidade de Terreiro'),
('d_ind_parc_mds_fam', '204', 'Familia Ribeirinha'),
('d_ind_parc_mds_fam', '205', 'Familia Agricultores Familiares'),
('d_ind_parc_mds_fam', '301', 'Familia Assentada da Reforma Agraria'),
('d_ind_parc_mds_fam', '302', 'Familia Beneficiaria do Programa Nacional do Credito Fundiario'),
('d_ind_parc_mds_fam', '303', 'Familia Acampada'),
('d_ind_parc_mds_fam', '304', 'Familia Atingida por Empreendimentos de Infraestrutura'),
('d_ind_parc_mds_fam', '305', 'Familia de Preso do Sistema Carcerario'),
('d_ind_parc_mds_fam', '306', 'Familia Catadores de Material Reciclavel'),
('d_ind_parc_mds_fam', '0', 'Nenhuma'),
('p_cod_est_cadastral_memb', '2', 'Sem Registro Civil'),
('p_cod_est_cadastral_memb', '3', 'Cadastrado'),
('p_cod_est_cadastral_memb', '5', 'Aguardando NIS'),
('p_cod_est_cadastral_memb', '6', 'Validando NIS'),
('p_ind_trabalho_infantil_pessoa', '1', 'Sim'),
('p_ind_trabalho_infantil_pessoa', '2', 'Nao'),
('p_cod_sexo_pessoa', '1', 'Masculino'),
('p_cod_sexo_pessoa', '2', 'Feminino'),
('p_cod_parentesco_rf_pessoa', '1', 'Pessoa Responsavel pela Unidade Familiar - RF'),
('p_cod_parentesco_rf_pessoa', '2', 'Conjuge ou companheiro(a)'),
('p_cod_parentesco_rf_pessoa', '3', 'Filho(a)'),
('p_cod_parentesco_rf_pessoa', '4', 'Enteado(a)'),
('p_cod_parentesco_rf_pessoa', '5', 'Neto(a) ou bisneto(a)'),
('p_cod_parentesco_rf_pessoa', '6', 'Pai ou mae'),
('p_cod_parentesco_rf_pessoa', '7', 'Sogro(a)'),
('p_cod_parentesco_rf_pessoa', '8', 'Irmao ou irma'),
('p_cod_parentesco_rf_pessoa', '9', 'Genro ou nora'),
('p_cod_parentesco_rf_pessoa', '10', 'Outro parente'),
('p_cod_parentesco_rf_pessoa', '11', 'Nao parente'),
('p_cod_raca_cor_pessoa', '1', 'Branca'),
('p_cod_raca_cor_pessoa', '2', 'Preta'),
('p_cod_raca_cor_pessoa', '3', 'Amarela'),
('p_cod_raca_cor_pessoa', '4', 'Parda'),
('p_cod_raca_cor_pessoa', '5', 'Indigena'),
('p_cod_local_nascimento_pessoa', '1', 'Neste municipio'),
('p_cod_local_nascimento_pessoa', '2', 'Em outro municipio'),
('p_cod_local_nascimento_pessoa', '3', 'Em outro pais'),
('p_cod_certidao_registrada_pessoa', '1', 'Sim e tem Certidao de Nascimento'),
('p_cod_certidao_registrada_pessoa', '2', 'Sim, mas nao tem Certidao de Nascimento'),
('p_cod_certidao_registrada_pessoa', '3', 'Nao'),
('p_cod_certidao_registrada_pessoa', '4', 'Nao sabe'),
('p_fx_idade', '0', 'Entre 0 e 4'),
('p_fx_idade', '1', 'Entre 5 a 6'),
('p_fx_idade', '2', 'Entre 7 a 15'),
('p_fx_idade', '3', 'Entre 16 a 17'),
('p_fx_idade', '4', 'Entre 18 a 24'),
('p_fx_idade', '5', 'Entre 25 a 34'),
('p_fx_idade', '6', 'Entre 35 a 39'),
('p_fx_idade', '7', 'Entre 40 a 44'),
('p_fx_idade', '8', 'Entre 45 a 49'),
('p_fx_idade', '9', 'Entre 50 a 54'),
('p_fx_idade', '10', 'Entre 55 a 59'),
('p_fx_idade', '11', 'Entre 60 a 64'),
('p_fx_idade', '12', 'Maior que  65'),
('p_marc_pbf', '0', 'Nao'),
('p_marc_pbf', '1', 'Sim'),
('p_ind_identidade_genero', '1', 'Sim'),
('p_ind_identidade_genero', '2', 'Nao'),
('p_ind_transgenero', '1', 'Sim, a pessoa e trans'),
('p_ind_transgenero', '2', 'Sim, a pessoa e travesti'),
('p_ind_transgenero', '3', 'Nao'),
('p_ind_tipo_identidade_genero', '1', 'Feminina'),
('p_ind_tipo_identidade_genero', '2', 'Masculina'),
('p_ind_tipo_identidade_genero', '3', 'Nao binario/a'),
('p_cod_certidao_civil_pessoa', '1', 'Nascimento'),
('p_cod_certidao_civil_pessoa', '2', 'Casamento'),
('p_cod_certidao_civil_pessoa', '3', 'RANI'),
('p_cod_deficiencia_memb', '1', 'Sim'),
('p_cod_deficiencia_memb', '2', 'Nao'),
('p_ind_def_cegueira_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_def_cegueira_memb', '1', 'Opcao marcada no formulario'),
('p_ind_def_baixa_visao_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_def_baixa_visao_memb', '1', 'Opcao marcada no formulario'),
('p_ind_def_surdez_profunda_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_def_surdez_profunda_memb', '1', 'Opcao marcada no formulario'),
('p_ind_def_surdez_leve_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_def_surdez_leve_memb', '1', 'Opcao marcada no formulario'),
('p_ind_def_fisica_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_def_fisica_memb', '1', 'Opcao marcada no formulario'),
('p_ind_def_mental_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_def_mental_memb', '1', 'Opcao marcada no formulario'),
('p_ind_def_sindrome_down_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_def_sindrome_down_memb', '1', 'Opcao marcada no formulario'),
('p_ind_def_transtorno_mental_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_def_transtorno_mental_memb', '1', 'Opcao marcada no formulario'),
('p_ind_ajuda_nao_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_ajuda_nao_memb', '1', 'Opcao marcada no formulario'),
('p_ind_ajuda_familia_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_ajuda_familia_memb', '1', 'Opcao marcada no formulario'),
('p_ind_ajuda_especializado_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_ajuda_especializado_memb', '1', 'Opcao marcada no formulario'),
('p_ind_ajuda_vizinho_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_ajuda_vizinho_memb', '1', 'Opcao marcada no formulario'),
('p_ind_ajuda_instituicao_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_ajuda_instituicao_memb', '1', 'Opcao marcada no formulario'),
('p_ind_ajuda_outra_memb', '0', 'Opcao nao marcada no formulario'),
('p_ind_ajuda_outra_memb', '1', 'Opcao marcada no formulario'),
('p_cod_sabe_ler_escrever_memb', '1', 'Sim'),
('p_cod_sabe_ler_escrever_memb', '2', 'Nao'),
('p_ind_frequenta_escola_memb', '1', 'Sim, rede publica'),
('p_ind_frequenta_escola_memb', '2', 'Sim, rede particular'),
('p_ind_frequenta_escola_memb', '3', 'Nao, ja frequentou'),
('p_ind_frequenta_escola_memb', '4', 'Nunca frequentou'),
('p_cod_escola_local_memb', '1', 'Sim'),
('p_cod_escola_local_memb', '2', 'Nao'),
('p_cod_curso_frequenta_memb', '1', 'Creche'),
('p_cod_curso_frequenta_memb', '2', 'Pre-escola (exceto CA)'),
('p_cod_curso_frequenta_memb', '3', 'Classe de Alfabetizacao - CA'),
('p_cod_curso_frequenta_memb', '4', 'Ensino Fundamental regular (duracao 8 anos)'),
('p_cod_curso_frequenta_memb', '5', 'Ensino Fundamental regular (duracao 9 anos)'),
('p_cod_curso_frequenta_memb', '6', 'Ensino Fundamental especial'),
('p_cod_curso_frequenta_memb', '7', 'Ensino Medio regular'),
('p_cod_curso_frequenta_memb', '8', 'Ensino Medio especial'),
('p_cod_curso_frequenta_memb', '9', 'Ensino Fundamental EJA - series iniciais (Supletivo - 1ª a 4ª)'),
('p_cod_curso_frequenta_memb', '10', 'Ensino Fundamental EJA - series finais (Supletivo - 5ª a 8ª)'),
('p_cod_curso_frequenta_memb', '11', 'Ensino Medio EJA (Supletivo)'),
('p_cod_curso_frequenta_memb', '12', 'Alfabetizacao para adultos(Mobral, etc.)'),
('p_cod_curso_frequenta_memb', '13', 'Superior, Aperfeicoamento,Especializacao, Mestrado,Doutorado'),
('p_cod_curso_frequenta_memb', '14', 'Pre-vestibular'),
('p_cod_ano_serie_frequenta_memb', '1', 'Primeiro(a)'),
('p_cod_ano_serie_frequenta_memb', '2', 'Segundo(a)'),
('p_cod_ano_serie_frequenta_memb', '3', 'Terceiro(a)'),
('p_cod_ano_serie_frequenta_memb', '4', 'Quarto(a)'),
('p_cod_ano_serie_frequenta_memb', '5', 'Quinto(a)'),
('p_cod_ano_serie_frequenta_memb', '6', 'Sexto(a)'),
('p_cod_ano_serie_frequenta_memb', '7', 'Setimo(a)'),
('p_cod_ano_serie_frequenta_memb', '8', 'Oitavo(a)'),
('p_cod_ano_serie_frequenta_memb', '9', 'Nono(a)'),
('p_cod_ano_serie_frequenta_memb', '10', 'Curso nao-seriado'),
('p_cod_curso_frequentou_pessoa_memb', '1', 'Creche'),
('p_cod_curso_frequentou_pessoa_memb', '2', 'Pre-escola (exceto CA)'),
('p_cod_curso_frequentou_pessoa_memb', '3', 'Classe de Alfabetizacao - CA'),
('p_cod_curso_frequentou_pessoa_memb', '4', 'Ensino Fundamental 1ª a 4ª series, Elementar (Primario), Primeira fase do 1º grau'),
('p_cod_curso_frequentou_pessoa_memb', '5', 'Ensino Fundamental 5ª a 8ª series, Medio 1º ciclo (Ginasial), Segunda fase do 1º grau'),
('p_cod_curso_frequentou_pessoa_memb', '6', 'Ensino Fundamental (duracao 9 anos)'),
('p_cod_curso_frequentou_pessoa_memb', '7', 'Ensino Fundamental Especial'),
('p_cod_curso_frequentou_pessoa_memb', '8', 'Ensino Medio, 2º grau, Medio 2º ciclo (Cientifico, Classico, Tecnico, Normal)'),
('p_cod_curso_frequentou_pessoa_memb', '9', 'Ensino Medio Especial'),
('p_cod_curso_frequentou_pessoa_memb', '10', 'Ensino Fundamental EJA -series iniciais (Supletivo 1ª a 4ª)'),
('p_cod_curso_frequentou_pessoa_memb', '11', 'Ensino Fundamental EJA -series finais (Supletivo 5ª a 8ª)'),
('p_cod_curso_frequentou_pessoa_memb', '12', 'Ensino Medio EJA(Supletivo)'),
('p_cod_curso_frequentou_pessoa_memb', '13', 'Superior, Aperfeicoamento,Especializacao, Mestrado,Doutorado'),
('p_cod_curso_frequentou_pessoa_memb', '14', 'Alfabetizacao para Adultos(Mobral, etc.)'),
('p_cod_curso_frequentou_pessoa_memb', '15', 'Nenhum'),
('p_cod_ano_serie_frequentou_memb', '1', 'Primeiro(a)'),
('p_cod_ano_serie_frequentou_memb', '2', 'Segundo(a)'),
('p_cod_ano_serie_frequentou_memb', '3', 'Terceiro(a)'),
('p_cod_ano_serie_frequentou_memb', '4', 'Quarto(a)'),
('p_cod_ano_serie_frequentou_memb', '5', 'Quinto(a)'),
('p_cod_ano_serie_frequentou_memb', '6', 'Sexto(a)'),
('p_cod_ano_serie_frequentou_memb', '7', 'Setimo(a)'),
('p_cod_ano_serie_frequentou_memb', '8', 'Oitavo(a)'),
('p_cod_ano_serie_frequentou_memb', '9', 'Nono(a)'),
('p_cod_ano_serie_frequentou_memb', '10', 'Curso nao-seriado'),
('p_cod_concluiu_frequentou_memb', '1', 'Sim'),
('p_cod_concluiu_frequentou_memb', '2', 'Nao'),
('p_grau_instrucao', '1', 'Sem instrucao'),
('p_grau_instrucao', '2', 'Fundamental incompleto'),
('p_grau_instrucao', '3', 'Fundamental completo'),
('p_grau_instrucao', '4', 'Medio incompleto'),
('p_grau_instrucao', '5', 'Medio completo'),
('p_grau_instrucao', '6', 'Superior incompleto ou mais'),
('p_cod_trabalhou_memb', '1', 'Sim'),
('p_cod_trabalhou_memb', '2', 'Nao'),
('p_cod_afastado_trab_memb', '1', 'Sim'),
('p_cod_afastado_trab_memb', '2', 'Nao'),
('p_cod_agricultura_trab_memb', '1', 'Sim'),
('p_cod_agricultura_trab_memb', '2', 'Nao'),
('p_cod_principal_trab_memb', '1', 'Trabalhador por conta propria (bico, autonomo)'),
('p_cod_principal_trab_memb', '2', 'Trabalhador temporario em area rural'),
('p_cod_principal_trab_memb', '3', 'Empregado sem carteira de trabalho assinada'),
('p_cod_principal_trab_memb', '4', 'Empregado com carteira de trabalho assinada'),
('p_cod_principal_trab_memb', '5', 'Trabalhador domestico sem carteira de trabalho assinada'),
('p_cod_principal_trab_memb', '6', 'Trab. domestico com cart. de trab. assinada'),
('p_cod_principal_trab_memb', '7', 'Trabalhador nao-remunerado'),
('p_cod_principal_trab_memb', '8', 'Militar ou servidor publico'),
('p_cod_principal_trab_memb', '9', 'Empregador'),
('p_cod_principal_trab_memb', '10', 'Estagiario'),
('p_cod_principal_trab_memb', '11', 'Aprendiz'),
('p_cod_trabalho_12_meses_memb', '1', 'Sim'),
('p_cod_trabalho_12_meses_memb', '2', 'Nao'),
('p_marc_sit_rua', '0', 'Nao'),
('p_marc_sit_rua', '1', 'Sim'),
('p_ind_dormir_rua_memb', '0', 'Nao'),
('p_ind_dormir_rua_memb', '1', 'Sim'),
('p_ind_dormir_albergue_memb', '0', 'Nao'),
('p_ind_dormir_albergue_memb', '1', 'Sim'),
('p_ind_dormir_dom_part_memb', '0', 'Nao'),
('p_ind_dormir_dom_part_memb', '1', 'Sim'),
('p_ind_outro_memb', '0', 'Nao'),
('p_ind_outro_memb', '1', 'Sim'),
('p_cod_tempo_rua_memb', '1', 'Ate seis meses'),
('p_cod_tempo_rua_memb', '2', 'Entre seis meses e um ano'),
('p_cod_tempo_rua_memb', '3', 'Entre um e dois anos'),
('p_cod_tempo_rua_memb', '4', 'Entre dois e cinco anos'),
('p_cod_tempo_rua_memb', '5', 'Entre cinco e dez anos'),
('p_cod_tempo_rua_memb', '6', 'Mais de dez anos'),
('p_ind_motivo_perda_memb', '0', 'Nao'),
('p_ind_motivo_perda_memb', '1', 'Sim'),
('p_ind_motivo_ameaca_memb', '0', 'Nao'),
('p_ind_motivo_ameaca_memb', '1', 'Sim'),
('p_ind_motivo_probs_fam_memb', '0', 'Nao'),
('p_ind_motivo_probs_fam_memb', '1', 'Sim'),
('p_ind_motivo_alcool_memb', '0', 'Nao'),
('p_ind_motivo_alcool_memb', '1', 'Sim'),
('p_ind_motivo_desemprego_memb', '0', 'Nao'),
('p_ind_motivo_desemprego_memb', '1', 'Sim'),
('p_ind_motivo_trabalho_memb', '0', 'Nao'),
('p_ind_motivo_trabalho_memb', '1', 'Sim'),
('p_ind_motivo_saude_memb', '0', 'Nao'),
('p_ind_motivo_saude_memb', '1', 'Sim'),
('p_ind_motivo_pref_memb', '0', 'Nao'),
('p_ind_motivo_pref_memb', '1', 'Sim'),
('p_ind_motivo_outro_memb', '0', 'Nao'),
('p_ind_motivo_outro_memb', '1', 'Sim'),
('p_ind_motivo_nao_sabe_memb', '0', 'Nao'),
('p_ind_motivo_nao_sabe_memb', '1', 'Sim'),
('p_ind_motivo_nao_resp_memb', '0', 'Nao'),
('p_ind_motivo_nao_resp_memb', '1', 'Sim'),
('p_cod_tempo_cidade_memb', '1', 'Ate seis meses'),
('p_cod_tempo_cidade_memb', '2', 'Entre seis meses e um ano'),
('p_cod_tempo_cidade_memb', '3', 'Entre um e dois anos'),
('p_cod_tempo_cidade_memb', '4', 'Entre dois e cinco anos'),
('p_cod_tempo_cidade_memb', '5', 'Entre cinco e dez anos'),
('p_cod_tempo_cidade_memb', '6', 'Mais de dez anos'),
('p_cod_vive_fam_rua_memb', '1', 'Sim'),
('p_cod_vive_fam_rua_memb', '2', 'Nao'),
('p_cod_contato_parente_memb', '1', 'Todo dia'),
('p_cod_contato_parente_memb', '2', 'Toda semana'),
('p_cod_contato_parente_memb', '3', 'Todo mes'),
('p_cod_contato_parente_memb', '4', 'Todo ano'),
('p_cod_contato_parente_memb', '5', 'Quase nunca'),
('p_cod_contato_parente_memb', '6', 'Nunca'),
('p_ind_ativ_com_escola_memb', '0', 'Nao'),
('p_ind_ativ_com_escola_memb', '1', 'Sim'),
('p_ind_ativ_com_coop_memb', '0', 'Nao'),
('p_ind_ativ_com_coop_memb', '1', 'Sim'),
('p_ind_ativ_com_mov_soc_memb', '0', 'Nao'),
('p_ind_ativ_com_mov_soc_memb', '1', 'Sim'),
('p_ind_ativ_com_nao_sabe_memb', '0', 'Nao'),
('p_ind_ativ_com_nao_sabe_memb', '1', 'Sim'),
('p_ind_ativ_com_nao_resp_memb', '0', 'Nao'),
('p_ind_ativ_com_nao_resp_memb', '1', 'Sim'),
('p_ind_atend_cras_memb', '0', 'Nao'),
('p_ind_atend_cras_memb', '1', 'Sim'),
('p_ind_atend_creas_memb', '0', 'Nao'),
('p_ind_atend_creas_memb', '1', 'Sim'),
('p_ind_atend_centro_ref_rua_memb', '0', 'Nao'),
('p_ind_atend_centro_ref_rua_memb', '1', 'Sim'),
('p_ind_atend_inst_gov_memb', '0', 'Nao'),
('p_ind_atend_inst_gov_memb', '1', 'Sim'),
('p_ind_atend_inst_nao_gov_memb', '0', 'Nao'),
('p_ind_atend_inst_nao_gov_memb', '1', 'Sim'),
('p_ind_atend_hospital_geral_memb', '0', 'Nao'),
('p_ind_atend_hospital_geral_memb', '1', 'Sim'),
('p_cod_cart_assinada_memb', '1', 'Sim'),
('p_cod_cart_assinada_memb', '2', 'Nao'),
('p_cod_cart_assinada_memb', '3', 'Nao Sabe'),
('p_ind_dinh_const_memb', '0', 'Nao'),
('p_ind_dinh_const_memb', '1', 'Sim'),
('p_ind_dinh_flanelhinha_memb', '0', 'Nao'),
('p_ind_dinh_flanelhinha_memb', '1', 'Sim'),
('p_ind_dinh_carregador_memb', '0', 'Nao'),
('p_ind_dinh_carregador_memb', '1', 'Sim'),
('p_ind_dinh_catador_memb', '0', 'Nao'),
('p_ind_dinh_catador_memb', '1', 'Sim'),
('p_ind_dinh_servs_gerais_memb', '0', 'Nao'),
('p_ind_dinh_servs_gerais_memb', '1', 'Sim'),
('p_ind_dinh_pede_memb', '0', 'Nao'),
('p_ind_dinh_pede_memb', '1', 'Sim'),
('p_ind_dinh_vendas_memb', '0', 'Nao'),
('p_ind_dinh_vendas_memb', '1', 'Sim'),
('p_ind_dinh_outro_memb', '0', 'Nao'),
('p_ind_dinh_outro_memb', '1', 'Sim'),
('p_ind_dinh_nao_resp_memb', '0', 'Nao'),
('p_ind_dinh_nao_resp_memb', '1', 'Sim'),
('p_ind_atend_nenhum_memb', '0', 'Nao'),
('p_ind_atend_nenhum_memb', '1', 'Sim')
ON CONFLICT (nome_campo, cod) DO UPDATE SET descricao = EXCLUDED.descricao;
